//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotionExporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotionExporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors: .
        /// </summary>
        internal static string About_AuthorsLbl {
            get {
                return ResourceManager.GetString("About_AuthorsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright: .
        /// </summary>
        internal static string About_CopyrightLbl {
            get {
                return ResourceManager.GetString("About_CopyrightLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load license.
        /// </summary>
        internal static string About_FailedToLoadLicense {
            get {
                return ResourceManager.GetString("About_FailedToLoadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load licenses.
        /// </summary>
        internal static string About_FailedToLoadLicenses {
            get {
                return ResourceManager.GetString("About_FailedToLoadLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        internal static string About_Libraries {
            get {
                return ResourceManager.GetString("About_Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License: .
        /// </summary>
        internal static string About_LicenseLbl {
            get {
                return ResourceManager.GetString("About_LicenseLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is made possible through the following third party libraries:.
        /// </summary>
        internal static string About_LicensesTxt {
            get {
                return ResourceManager.GetString("About_LicensesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Notion Exporter.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool for exporting pages and database from Notion..
        /// </summary>
        internal static string About_TxtLine1 {
            get {
                return ResourceManager.GetString("About_TxtLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2023 Ryan Bester..
        /// </summary>
        internal static string About_TxtLine2 {
            get {
                return ResourceManager.GetString("About_TxtLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool is not affiliated with Notion Labs, Inc..
        /// </summary>
        internal static string About_TxtLine3 {
            get {
                return ResourceManager.GetString("About_TxtLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Details.
        /// </summary>
        internal static string CopyDetails {
            get {
                return ResourceManager.GetString("CopyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time.
        /// </summary>
        internal static string CreatedTime {
            get {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        internal static string Databases {
            get {
                return ResourceManager.GetString("Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Columns....
        /// </summary>
        internal static string EditColumns {
            get {
                return ResourceManager.GetString("EditColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All.
        /// </summary>
        internal static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Modules.
        /// </summary>
        internal static string ExportProfileControls_IncludeModules {
            get {
                return ResourceManager.GetString("ExportProfileControls_IncludeModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all modules and versions in the export. Useful when sharing profiles..
        /// </summary>
        internal static string ExportProfileControls_IncludeModulesTooltip {
            get {
                return ResourceManager.GetString("ExportProfileControls_IncludeModulesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Queue.
        /// </summary>
        internal static string ExportQueue {
            get {
                return ResourceManager.GetString("ExportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        internal static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: .
        /// </summary>
        internal static string FilterLbl {
            get {
                return ResourceManager.GetString("FilterLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Form_CancelBtn {
            get {
                return ResourceManager.GetString("Form_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Form_CloseBtn {
            get {
                return ResourceManager.GetString("Form_CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Form_OKBtn {
            get {
                return ResourceManager.GetString("Form_OKBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &gt;&gt;.
        /// </summary>
        internal static string InputTab_AddBtn {
            get {
                return ResourceManager.GetString("InputTab_AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Remove.
        /// </summary>
        internal static string InputTab_RemoveBtn {
            get {
                return ResourceManager.GetString("InputTab_RemoveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selection in Profile.
        /// </summary>
        internal static string InputTab_SaveSelectionInProfile {
            get {
                return ResourceManager.GetString("InputTab_SaveSelectionInProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Edited By.
        /// </summary>
        internal static string LastEditedBy {
            get {
                return ResourceManager.GetString("LastEditedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Edited Time.
        /// </summary>
        internal static string LastEditedTime {
            get {
                return ResourceManager.GetString("LastEditedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        internal static string NameLbl {
            get {
                return ResourceManager.GetString("NameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0}.
        /// </summary>
        internal static string NewProfileForm_DuplicateTitle {
            get {
                return ResourceManager.GetString("NewProfileForm_DuplicateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename {0}.
        /// </summary>
        internal static string NewProfileForm_RenameTitle {
            get {
                return ResourceManager.GetString("NewProfileForm_RenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        internal static string NewProfileForm_Title {
            get {
                return ResourceManager.GetString("NewProfileForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notion Exporter.
        /// </summary>
        internal static string NotionExporter {
            get {
                return ResourceManager.GetString("NotionExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read settings: {0}.
        /// </summary>
        internal static string NotionExporter_FailedToReadSettings {
            get {
                return ResourceManager.GetString("NotionExporter_FailedToReadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Notion API Key must be configured to use this application. Would you like to configure it now?.
        /// </summary>
        internal static string NotionExporter_KeyMustBeConfigured {
            get {
                return ResourceManager.GetString("NotionExporter_KeyMustBeConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder....
        /// </summary>
        internal static string OpenLogFolderBtn {
            get {
                return ResourceManager.GetString("OpenLogFolderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile: .
        /// </summary>
        internal static string ProfileLbl {
            get {
                return ResourceManager.GetString("ProfileLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Manager.
        /// </summary>
        internal static string ProfileManager {
            get {
                return ResourceManager.GetString("ProfileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string ProfileManager_Activate {
            get {
                return ResourceManager.GetString("ProfileManager_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string ProfileManager_Duplicate {
            get {
                return ResourceManager.GetString("ProfileManager_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Manager....
        /// </summary>
        internal static string ProfileManagerBtn {
            get {
                return ResourceManager.GetString("ProfileManagerBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string ProfileManagerForm_DeleteTitle {
            get {
                return ResourceManager.GetString("ProfileManagerForm_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        internal static string ProfileManagerForm_DeleteTxt {
            get {
                return ResourceManager.GetString("ProfileManagerForm_DeleteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Profile.
        /// </summary>
        internal static string ProfileManagerForm_ExportProfile {
            get {
                return ResourceManager.GetString("ProfileManagerForm_ExportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile exported successfully.
        /// </summary>
        internal static string ProfileManagerForm_ExportProfileSuccess {
            get {
                return ResourceManager.GetString("ProfileManagerForm_ExportProfileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0}.
        /// </summary>
        internal static string ProfileManagerForm_ExportTitle {
            get {
                return ResourceManager.GetString("ProfileManagerForm_ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Profile.
        /// </summary>
        internal static string ProfileManagerForm_ImportProfile {
            get {
                return ResourceManager.GetString("ProfileManagerForm_ImportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profile already exists with this name..
        /// </summary>
        internal static string ProfileManagerForm_ImportProfileAlreadyExists {
            get {
                return ResourceManager.GetString("ProfileManagerForm_ImportProfileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile imported successfully.
        /// </summary>
        internal static string ProfileManagerForm_ImportProfileSuccess {
            get {
                return ResourceManager.GetString("ProfileManagerForm_ImportProfileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query: .
        /// </summary>
        internal static string QueryLbl {
            get {
                return ResourceManager.GetString("QueryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository: .
        /// </summary>
        internal static string RepositoryLbl {
            get {
                return ResourceManager.GetString("RepositoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Settings.
        /// </summary>
        internal static string RestoreSettings {
            get {
                return ResourceManager.GetString("RestoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a log event above to view details.
        /// </summary>
        internal static string SelectLogEvent_DetailsTxt {
            get {
                return ResourceManager.GetString("SelectLogEvent_DetailsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default.
        /// </summary>
        internal static string SetDefault {
            get {
                return ResourceManager.GetString("SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string Settings_Authorization {
            get {
                return ResourceManager.GetString("Settings_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and Restore.
        /// </summary>
        internal static string Settings_BackupAndRestore {
            get {
                return ResourceManager.GetString("Settings_BackupAndRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create backup: {0}.
        /// </summary>
        internal static string Settings_BackupFailed {
            get {
                return ResourceManager.GetString("Settings_BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Settings.
        /// </summary>
        internal static string Settings_BackupSettings {
            get {
                return ResourceManager.GetString("Settings_BackupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created successfully.
        /// </summary>
        internal static string Settings_BackupSuccessful {
            get {
                return ResourceManager.GetString("Settings_BackupSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup file will contain sensitive information, such as your Notion key. Do not distribute this file..
        /// </summary>
        internal static string Settings_BackupWarning {
            get {
                return ResourceManager.GetString("Settings_BackupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns: .
        /// </summary>
        internal static string Settings_ColumnsLbl {
            get {
                return ResourceManager.GetString("Settings_ColumnsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore backup: {0}.
        /// </summary>
        internal static string Settings_RestoreFailed {
            get {
                return ResourceManager.GetString("Settings_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored successfully. Please restart Notion Exporter..
        /// </summary>
        internal static string Settings_RestoreSuccessful {
            get {
                return ResourceManager.GetString("Settings_RestoreSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore all settings in {0}. This will overwrite all local data..
        /// </summary>
        internal static string Settings_RestoreWarning {
            get {
                return ResourceManager.GetString("Settings_RestoreWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string SettingsBtn {
            get {
                return ResourceManager.GetString("SettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The backup file will contain sensitive information such as your Notion key..
        /// </summary>
        internal static string SettingsForm_BackupRestoreTxt {
            get {
                return ResourceManager.GetString("SettingsForm_BackupRestoreTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Icons.
        /// </summary>
        internal static string SettingsForm_LoadIcons {
            get {
                return ResourceManager.GetString("SettingsForm_LoadIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notion Key: .
        /// </summary>
        internal static string SettingsForm_NotionKeyLbl {
            get {
                return ResourceManager.GetString("SettingsForm_NotionKeyLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integration must have the Read Content, Read Comments, and Read User Information permissions..
        /// </summary>
        internal static string SettingsForm_NotionKeyTxt {
            get {
                return ResourceManager.GetString("SettingsForm_NotionKeyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string SettingsForm_Permission {
            get {
                return ResourceManager.GetString("SettingsForm_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string SettingsForm_Test {
            get {
                return ResourceManager.GetString("SettingsForm_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string SettingsForm_ThemeDark {
            get {
                return ResourceManager.GetString("SettingsForm_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follows System.
        /// </summary>
        internal static string SettingsForm_ThemeFollowsSystem {
            get {
                return ResourceManager.GetString("SettingsForm_ThemeFollowsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string SettingsForm_ThemeLight {
            get {
                return ResourceManager.GetString("SettingsForm_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsForm_Title {
            get {
                return ResourceManager.GetString("SettingsForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size All Columns to Fit.
        /// </summary>
        internal static string SizeAllColumnsToFit {
            get {
                return ResourceManager.GetString("SizeAllColumnsToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort: .
        /// </summary>
        internal static string SortLbl {
            get {
                return ResourceManager.GetString("SortLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0}The application will now quit..
        /// </summary>
        internal static string UnhandledException_ApplicationQuit {
            get {
                return ResourceManager.GetString("UnhandledException_ApplicationQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0}{1} at {2}: {3}{0}{0}Check the application logs for more details..
        /// </summary>
        internal static string UnhandledException_CheckLogs {
            get {
                return ResourceManager.GetString("UnhandledException_CheckLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred..
        /// </summary>
        internal static string UnhandledException_Occurred {
            get {
                return ResourceManager.GetString("UnhandledException_Occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: .
        /// </summary>
        internal static string URLLbl {
            get {
                return ResourceManager.GetString("URLLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use System Language.
        /// </summary>
        internal static string UseSystemLanguage {
            get {
                return ResourceManager.GetString("UseSystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        internal static string Verbose {
            get {
                return ResourceManager.GetString("Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string VersionLbl {
            get {
                return ResourceManager.GetString("VersionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
